"use strict";
import { BaseContract, Contract, ContractFactory } from "@ethersfathom/contracts";
import { BigNumber, FixedNumber } from "@ethersfathom/bignumber";
import { Signer, VoidSigner } from "@ethersfathom/abstract-signer";
import { Wallet } from "@ethersfathom/wallet";
import * as constants from "@ethersfathom/constants";
import * as providers from "@ethersfathom/providers";
import { getDefaultProvider } from "@ethersfathom/providers";
import { Wordlist, wordlists } from "@ethersfathom/wordlists";
import * as utils from "./utils";
import { ErrorCode as errors, Logger } from "@ethersfathom/logger";
////////////////////////
// Compile-Time Constants
// This is generated by "npm run dist"
import { version } from "./_version";
const logger = new Logger(version);
////////////////////////
// Exports
export { Signer, Wallet, VoidSigner, getDefaultProvider, providers, BaseContract, Contract, ContractFactory, BigNumber, FixedNumber, constants, errors, logger, utils, wordlists, 
////////////////////////
// Compile-Time Constants
version, Wordlist };
//# sourceMappingURL=ethers.js.map