"use strict";
import { BaseContract, Contract, ContractFactory } from "@into-the-fathom/contracts";
import { BigNumber, FixedNumber } from "@into-the-fathom/bignumber";
import { Signer, VoidSigner } from "@into-the-fathom/abstract-signer";
import { Wallet } from "@into-the-fathom/wallet";
import * as constants from "@into-the-fathom/constants";
import * as providers from "@into-the-fathom/providers";
import { getDefaultProvider } from "@into-the-fathom/providers";
import { Wordlist, wordlists } from "@into-the-fathom/wordlists";
import * as utils from "./utils";
import { ErrorCode as errors, Logger } from "@into-the-fathom/logger";
////////////////////////
// Compile-Time Constants
// This is generated by "npm run dist"
import { version } from "./_version";
const logger = new Logger(version);
////////////////////////
// Exports
export { Signer, Wallet, VoidSigner, getDefaultProvider, providers, BaseContract, Contract, ContractFactory, BigNumber, FixedNumber, constants, errors, logger, utils, wordlists, 
////////////////////////
// Compile-Time Constants
version, Wordlist };
//# sourceMappingURL=ethers.js.map