"use strict";
import { BaseContract, Contract, ContractFactory } from "@baldyash/contracts";
import { BigNumber, FixedNumber } from "@baldyash/bignumber";
import { Signer, VoidSigner } from "@baldyash/abstract-signer";
import { Wallet } from "@baldyash/wallet";
import * as constants from "@baldyash/constants";
import * as providers from "@baldyash/providers";
import { getDefaultProvider } from "@baldyash/providers";
import { Wordlist, wordlists } from "@baldyash/wordlists";
import * as utils from "./utils";
import { ErrorCode as errors, Logger } from "@baldyash/logger";
////////////////////////
// Compile-Time Constants
// This is generated by "npm run dist"
import { version } from "./_version";
const logger = new Logger(version);
////////////////////////
// Exports
export { Signer, Wallet, VoidSigner, getDefaultProvider, providers, BaseContract, Contract, ContractFactory, BigNumber, FixedNumber, constants, errors, logger, utils, wordlists, 
////////////////////////
// Compile-Time Constants
version, Wordlist };
//# sourceMappingURL=ethers.js.map